services:
  backend:
    build:
      context: ./backend
      target: builder        # stop di build stage, jangan run stage
    volumes:
      - ./backend:/app       # hot reload
    ports:
      - "8080:8080"
    env_file:
    - ./backend/.env
    command: air             # pakai Air buat hot reload
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"          # expose ke host buat akses dari TablePlus/DBeaver
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: